language: ruby
bundler_args: --without production development
rvm:
  - 2.1.2
env:
  - "DATABASE_URL=postgres://postgres/travis_ci_test"
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
script: bundle exec rspec
